### ISSUE TITLE
Missing field 'cross_posts'

### ISSUE THREAD

**Issue by macniel** [lemmygtk/lemoa#13]
I am on [feddit.de](https://feddit.de) (BE 0.17.4) and everytime I click on a post I get the following error message:

`error decoding response body: missing field 'cross_posts' at line 1 column 4220`

Is there a way to send actual logs that you can use for debugging purposes?

**Comment by Bnyro** [comment]
Unfortunately the only way for it to become fixed is to wait for feddit.de to update to 0.18.0. We're using the `lemmy_api_common` library which provides the data types we need for connecting to lemmy.
I'll try to wait longer before updating the Api version we use next time. It's very unfortunate that new versions of the lemmy api aren't compatible with older ones :(

**Comment by macniel** [comment]
Oh, and `lemmy_api_common` can't handle both version? That's a bit sad, not gonna lie.

**Comment by Bnyro** [comment]
Yes, unfortunately :(
