### ISSUE TITLE
Lemoa run through flatpak doesn't respect gtk theme

### ISSUE THREAD

**Issue by hughrawlinson** [lemmygtk/lemoa#14]
Hi! Please let me know if this is actually an issue for Flatpak. When I run Lemoa by compiling the rust and launching the release binary that's generated, Lemoa runs with my correct theme. But, when I run the copy I installed with Flatpak, it runs with a different, light-mode theme. Not sure why that would be. I've set the theme correctly with `gsettings` and in `~/.config/gtk-4.0/settings.ini` (and the 3.0 equivalent directory). All other apps seem to respect my theme. I'm on Ubuntu 23.04 and using i3wm.

Thanks for working on this project!

**Comment by Bnyro** [comment]
I have the same issue when running the app as Flatpak (also with some other apps).
I suspect we need some extract code to detect which theme we should use when running under Flatpak, but unfortunately I don't really know how we can figure out which theme the desktop prefers when running Flatpak.
When not running as Flatpak, Gtk automatically applies the correct theme.

**Comment by Bnyro** [comment]
It seems like you can run
```
flatpak override --filesystem=/usr/share/themes/
sudo flatpak override --env GTK_THEME=Adwaita-dark
```
and apply whatever theme you're using.
At least it worked for me that way.

**Comment by hughrawlinson** [comment]
That worked! Would it be worth writing this into the docs somewhere? Or into the description of the flatpak install instructions?

**Comment by Bnyro** [comment]
Yes, I think this would be a good idea!
