### ISSUE TITLE
Make application more adaptive

### ISSUE THREAD

**Issue by Shatur** [lemmygtk/lemoa#17]
I trying to run the application on my phone on Plasma Mobile. Here is how it looks in horizontal and vertical modes:
![Screenshot_20230706_103751](https://github.com/lemmygtk/lemoa/assets/22453358/3e2d0717-aa05-49d9-bdda-bfa5c66c881e)
![Screenshot_20230706_103728](https://github.com/lemmygtk/lemoa/assets/22453358/4fb690b4-44c0-4fe9-b415-ff48b9f0a303)

The issues is that in horizontal mode there is no View button and in vertical mode the text is also displayed partially.
Could you make posts more adaptive?
Ideal solution would be to use [libhandy](https://gitlab.gnome.org/GNOME/libhandy) (more modern) instead of libadwaita, but I understand that you may don't want to change the core library.

**Comment by Bnyro** [comment]
Fyi, the "view" button has been removed in 0.2.0 in favor of just clicking the title of the post instead.
The app uses [Relm4](https://relm4.org/), therefore I don't think it's possible to use libhandy as I don't think Relm4 supports it. Libadwaita doesn't look good in my opinion, therefore we currently use vanilla gtk4.

**Comment by Shatur** [comment]
> Fyi, the "view" button has been removed in 0.2.0 in favor of just clicking the title of the post instead.

Got it, thanks. That it would be nice to just make the text wrap the screen, it should solve most of the problems.
Here is how posts look:
![Screenshot_20230706_113600](https://github.com/lemmygtk/lemoa/assets/22453358/608a29b7-6d1b-4b24-a397-f01dbfbf0275)

**Comment by Bnyro** [comment]
done with https://github.com/lemmygtk/lemoa/commit/bfe570a0fce1aaed1647fa5bed39b89cd91ca1e1.

**Comment by Shatur** [comment]
Thank you a lot, way better now!
![Screenshot_20230706_142834](https://github.com/lemmygtk/lemoa/assets/22453358/03f6e77b-d0e8-4bf3-820c-80372f0746dc)
Yes, the post does not fit because of long user name, but I can scroll to the right.

But when the back button appears it makes the app does not fit the screen:
![Screenshot_20230706_143019](https://github.com/lemmygtk/lemoa/assets/22453358/843a0739-1171-4c61-8f53-e247a69f35d5)

May I ask you to make buttons configurable? If I communities could be hidden in sandwich menu (three dots), it will work fine.
Or as alternative - detect if a screen is small and move communities to sandwich.

**Comment by Shatur** [comment]
Never mind, I found a way to hide close / minimize / maximize buttons.

**Comment by Shatur** [comment]
One more request (sorry!). Could you rearrange these buttons inside the post horizontally or make them wrap?
![Screenshot_20230706_143651](https://github.com/lemmygtk/lemoa/assets/22453358/c5e76472-581d-43bc-81d3-7c3f1a8bc3be)

**Comment by Bnyro** [comment]
Hmm, the items in the top bar will still overflow when you're logged in, since we have 4 items in the top bar then.

**Comment by Shatur** [comment]
> Hmm, the items in the top bar will still overflow when you're logged in, since we have 4 items in the top bar then.

Let me check it...

**Comment by Shatur** [comment]
You were right :(

![Screenshot_20230706_144436](https://github.com/lemmygtk/lemoa/assets/22453358/335edb72-7b79-4790-9409-7cd0c6a92d93)

The suggestion about authohide some buttons to sandwich is relevant.

**Comment by Bnyro** [comment]
> One more request (sorry!). Could you rearrange these buttons inside the post horizontally or make them wrap? ![Screenshot_20230706_143651](https://user-images.githubusercontent.com/22453358/251438447-c5e76472-581d-43bc-81d3-7c3f1a8bc3be.png)
>
Done!

**Comment by Bnyro** [comment]
Not sure what we can do about the top bar.
I planned to remove the "Recommended" tab in the top bar soon in favor of a dedicated filter menu for posts, so there will be only three visible tabs. Maybe we can just move the inbox to the right then? 
(Home and communities at the left, inbox at the right)

**Comment by Shatur** [comment]
>   (Home and communities at the left, inbox at the right)

Yes, three tabs should fit the screen.

**Comment by Shatur** [comment]
Should I open a separate issue in order to track it?

**Comment by Bnyro** [comment]
No, you don't have to.

**Comment by Hacker1245** [comment]
Just wanted to hook myself up to this issue to share how it looks with 250% scaling on Phosh.
![Screenshot from 2023-08-04 21-54-51](https://github.com/lemmygtk/lemoa/assets/29224894/86be51e8-5796-4174-9494-2cccdd187ce0)
![Screenshot from 2023-08-04 21-54-41](https://github.com/lemmygtk/lemoa/assets/29224894/68e7339f-f1b1-487f-9585-3cbf6cc1c930)

**Comment by Shatur** [comment]
@Hacker1245, yeah, we probably need something written using libhandy or other mobile friendly library. It will be hard for the author to make it usable for both PC and mobile.

**Comment by Shatur** [comment]
Actually, relm4 supports `libadwaita` which is successor to `libhandy`. I will try it and write you back.

**Comment by Shatur** [comment]
Tried it out - same problem, I need to scroll horizontally to see the full text.
