### ISSUE TITLE
Provide a build with libadwaita

### ISSUE THREAD

**Issue by marc0x1** [lemmygtk/lemoa#19]
or dynamically load it if the de is gnome

**Comment by gianni-rosato** [comment]
You could combine efforts with [Lemonade](https://github.com/mdwalters/lemonade), which is already a GTK4 native Lemmy client.

**Comment by Bnyro** [comment]
I don't mind if Lemonade's owner wants to join the development here, however Lemoa is currently way more feature rich than Lemonade.
And Lemoa is a native Gtk4 client as well.
Apart from that, Rust is very different to Python and I don't think the code is comparable.

**Comment by Bnyro** [comment]
You can build the app using libadwaita yourself by changing
```
relm4 = 0.6.0
```
to
```
relm4 = { version = "0.6.0", features = ["libadwaita"] }
```
in Cargo.toml.

For instructions on how to build the app, please see the README.
Since we currently don't provide prebuilt binaries via GitHub releases, I don't think there's a better way than just letting you build it yourself.

**Comment by gianni-rosato** [comment]
For the Flatpak, could u distribute with libadwaita?

**Comment by Bnyro** [comment]
I'm not sure if that's possible, I guess we would need to create a new PR on flathub to add it as a new app?
Also, are there any other apps on Flathub that provide two different builds?

**Comment by gianni-rosato** [comment]
If not, it is definitely still possible & would be really cool to see as it gives the users more flexibility in choosing their favorite option
