### ISSUE TITLE
build error "Package libadwaita-1 was not found in the pkg-config search path."

### ISSUE THREAD

**Issue by shellheim** [lemmygtk/lemoa#22]
I was trying to test this as an rpm. Before that I tried to build it normally using meson but the build failed due to me not having openssl but after installing it using `sudo dnf install openssl` the build continued and then again in the middle of compiling crates it failed due to a package called `libadwaita-1`.

I tried finding in on fedora but couldn't, the searches don't help either. It would be great if you could help me out.

**Comment by Bnyro** [comment]
I think the package that needs to be installed is called `libadwaita-devel` on rpm distros, but I might be wrong.

**Comment by shellheim** [comment]
thanks for the very swift response, that indeed seems to be it!
Now it built and it works as expected.
Do I have to list all the crates as building dependencies when building the rpm? Shouldn't they be downloaded automatically? Was libadwaita a crate or a normal package? Again, thanks for the help. Closing as completed.

**Comment by Bnyro** [comment]
> Do I have to list all the crates as building dependencies when building the rpm? Shouldn't they be downloaded automatically? Was libadwaita a crate or a normal package? Again, thanks for the help. Closing as completed.
>
Some rust crates (=libraries) depend on C development packages, such as libadwaita-devel. Therefore they're needed during compilation. libadwaita is a normal package, whereas there are rust bindings for it, that allow using it in Rust although it's written in C. Though you only have to install the C library libadwaita-devel, rust automatically downloads the bindings it needs.

And no, these aren't downloaded automatically. For reference the void linux template: https://github.com/void-linux/void-packages/blob/master/srcpkgs/lemoa/template

**Comment by shellheim** [comment]
oh! thanks for the template. I read the packaging [docs](https://github.com/void-linux/void-packages/blob/master/Manual.md#optional-variables) for void. They specify two types of dependencies `host` and `target`. In rpm packaging there are `runtime` and `compiletime` dependencies (no the same name). But both the void types seem to be for compiling.

**Comment by Bnyro** [comment]
`hostmakedepends` and `makedepends` are only needed for compilation, yes.

`depends` is needed during runtime.

**Comment by shellheim** [comment]
Thanks!

**Comment by shellheim** [comment]
A few questions on the packages : 

the `rust-std` package is the name of the standard library for rust in void right?
`libglib-devel` is the gtk library?

**Comment by Bnyro** [comment]
Yes, `rust-std` shouldn't be needed for distros other than Void.

`glib-devel` should be sufficient for building it.

`pkg-config` is needed for the rust bindings to locate the required C libraries on your machine (mostly gtk and libadwaita)

**Comment by shellheim** [comment]
Okay, finally! Built the binary rpm and the srpm and a binary rpm from that and tested both. Works as expected. I will install and test the .rpm tommorrow. I also added `openssl-devel` as a dependency because it wouldn't compile without that. 

[spec file](https://codeberg.org/shellheim/lemoa-rpm-package/src/branch/main/lemoa.spec)

**Comment by Bnyro** [comment]
Cool, glad it works for you now!
