### ISSUE TITLE
Uninstall target?

### ISSUE THREAD

**Issue by shellheim** [lemmygtk/lemoa#23]
I built lemoa from source to test, but I don't know how to uninstall. `make uninstall` doesn't seem to know the uninstall target. I think this should be added to the building section in README.md

**Comment by Bnyro** [comment]
The app is meant to be installed via the distro package manager mostly which handles that itself. The recommended way to install it is flatpak, if not in the distro repo.

Nevertheless you can just remove all the files that are printed in the log when installing it.

**Comment by shellheim** [comment]
okay, thanks for the help!
