### ISSUE TITLE
Get Federated Instances

### ISSUE THREAD

**Issue by thebigG** [lemmygtk/lemoa#3]
Are there plans to just fetch the federated instances with something like https://join-lemmy.org/api/interfaces/FederatedInstances.html#allowed api call, which I think would be the call to make in order to get a list like there is on https://join-lemmy.org/instances?

If the answer is yes, it don't look too hard--I can probably take a stab at it. But I want to double check that this is the intent of the project before I write a bunch of code.

Thanks

**Comment by Bnyro** [comment]
Depends on where you are planning to use this. Do you want to use it for the selection of an instance at the beginning, so that we can suggest a list of known instances a user can choose from? That would makes sense to me. I don't know if there is an other purpose for that.

**Comment by thebigG** [comment]
> Do you want to use it for the selection of an instance at the beginning, so that we can suggest a list of known instances a user can choose from?

Yes. This was exactly what I was thinking. Instead of having of type a URL(which we could keep as an option?), the user would just select an instance from the list.

**Comment by Bnyro** [comment]
Sounds great!
