### ISSUE TITLE
error decoding response body

### ISSUE THREAD

**Issue by norayr** [lemmygtk/lemoa#33]
i just installed lemoa-0.5.0-r0 on postmarketos.

when logging in to my instance, i get 'error decoding response body: trailing input at line 1 column 384'.

and 'go back' button is showed under that message.

when i press it, column number changes to 422.

is it because my lemoa version is too old?

**Comment by Bnyro** [comment]
Which Lemmy version does your selected instance use? We use version 0.18 of the Lemmy API, so Lemmy 0.19 might be incompatible with the current release.

**Comment by norayr** [comment]
indeed, the page says
```
UI: 0.19.1-rc.1
BE: 0.19.1-rc.2
```

thank you.

**Comment by Bnyro** [comment]
I'll take a look at migrating to v0.19 after my vacation :+1:

**Comment by LSeelig** [comment]
I am having this issue in reverse. My server is on version 0.18.5, and I am getting "error decoding response body: input is not enough for unique date and time at line 1 column 250"

**Comment by Bnyro** [comment]
See pinned issue.

**Comment by LSeelig** [comment]
Thank you. I did not check that because I logged in just fine; the issue came afterwards. I apologize.
