### ISSUE TITLE
Can't login to an instance at 0.18.5

### ISSUE THREAD

**Issue by shellheim** [lemmygtk/lemoa#34]
Trying to login at an instance at version `0.18.5`, I get the error : `error decoding response body: input is not enough for unique date and time at line 1 column 256`

Is the backwards compatibility with pre 0.19 versions completely severed? If yes then keeping this issue would be helpful to other people facing the same problem.

**Comment by Bnyro** [comment]
> Is the backwards compatibility with pre 0.19 versions completely severed? If yes then keeping this issue would be helpful to other people facing the same problem.
>
Yes, unfortunately the new Lemmy update contains breaking changes so that older instance versions are no longer compatible. Please stick with Lemoa 0.5.0 until the instance you use is upgraded.

**Comment by shellheim** [comment]
Ah, thanks for the quick reply!

**Comment by Kawirs** [comment]
excuse I have the same issue, how do I go to 0.5.0? I just installed Lemoa in debian 12 via flatpak
