### ISSUE TITLE
Error upon signing in or selecting instance

### ISSUE THREAD

**Issue by jerrythegenius** [lemmygtk/lemoa#35]
I entered "lemmy.world" (I also tried "https://lemmy.world/") as  the instance url (I tried with both the "public" and "custom" tabs) and now this error is showing in the "posts" of the application. This is with the flatpak version of lemoa 0.5.1 on fedora workstation 39 x86_64 with gnome 45.3. A similar error occured in a few other parts of the application-- the "communities" tab says "line 1 column 1273", and the "site info" section says "line 1 column 3418". The "change instance", "accounts", "login", "profile", "settings", and "about" section look as expected (other than being unable to sign in). These errors did not occur when using "lemmy.ml" as the instance.

A screenshot of the "posts" section:
![image](https://github.com/lemmygtk/lemoa/assets/130116916/650df18b-ac8f-435d-8348-2517ccb85038)
(sorry if this should have been sent to lemmy.world rather than you guys)

**Comment by jerry-the-genius** [comment]
Nevermind, I just figured it out: lemmy.world is still on 0.18.5. I'll talk to them about it.
